[package]
name = "javero"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
serde = { version = "1", features = ["derive"]}
serde_json = "1"
reqwest = { version = "0.12" }
tokio = { version = "1", features = ["full"] }